Currently Loaded Modulefiles:
  1) python/3.7
Traceback (most recent call last):
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "stochastic-super-tight-smallepsilonm.py", line 64, in <module>
    experiment()
  File "stochastic-super-tight-smallepsilonm.py", line 59, in experiment
    parallel_run=True, n_processes=None)
  File "/home/disc/e.lecarpentier/git/llrl/llrl/experiments.py", line 110, in run_agents_lifelong
    lifelong_plot(agents, path, n_tasks, n_episodes, confidence, open_plot, plot_title)
  File "/home/disc/e.lecarpentier/git/llrl/llrl/utils/chart_utils.py", line 76, in lifelong_plot
    plot_title=plot_title)
  File "/home/disc/e.lecarpentier/git/llrl/llrl/utils/chart_utils.py", line 140, in plot
    plt.savefig(plot_file_name, format='pdf')
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 716, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
    self.figure.draw(renderer)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2605, in draw
    self._update_title_position(renderer)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2554, in _update_title_position
    if title.get_window_extent(renderer).ymin < top:
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/backends/_backend_pdf_ps.py", line 47, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "/home/disc/e.lecarpentier/.conda/envs/myenv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 308, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because latex could not be found
